### ISSUE TITLE
Board disappears when User Defined Target leaves camera view

### ISSUE THREAD

**Issue by wallacepreston** [bad-bots/towar-defense#11]
Story: 
As a user, when I define a target, it leaves the field of view of the camera, the board currently goes away, then re-appears when UDT comes back into view.  The board should persist, even when UDT goes out of field of view of camera.

Implementation: 
- [ ] Talk to Omri/Fellow about alternatives to Ground Plane Tracking or User Defined Targets.  
- [ ] Is there a better way to get the board to appear on the ground and stay there?

**Comment by mattwc93** [comment]
Figured out the option to fix this for the moment!
