### ISSUE TITLE
Update/Polish unit physics

### ISSUE THREAD

**Issue by mattwc93** [bad-bots/towar-defense#33]
Fix "quirks" in unit physics. 
**Current behavior:** 

- Units "slide" along ground and randomly speed up near enemy tower. 
- Sometimes when they collide they start "flying"

**Expect behavior:**

- Unit should have set speed regardless of proximity to target. 
- Units should have gravity and not bounce off one another. 
- Unit will travel around obstacle rather than "jumping" over them.
- When unit reaches its current target it should stop moving and fight.

**Comment by scottbot95** [comment]
This should have been resolved a little while ago.
