### ISSUE TITLE
Ensure All Team Members have Same Work Environment

### ISSUE THREAD

**Issue by wallacepreston** [bad-bots/towar-defense#8]
Basically, let's make sure we're all on the same page in our environment!  

To Test
- [x] Do we all have the same Unity version?
- [x] Vuforia version? 
- [x] All pulling and pushing to the same place?

List of Machines
- [x] Scott's machine
- [x] Matt's machine
- [x] Preston's machine
- [x] Duncan's machine

**Comment by scottbot95** [comment]
- Unity 2018.3.3 
- Vufoia 8.0.10
