### ISSUE TITLE
Test basic build/run on all 4 phones works 

### ISSUE THREAD

**Issue by wallacepreston** [bad-bots/towar-defense#9]
Ensure the same version of code we all have builds and runs on our phones as desired.  Little bugs are not important, but getting some semblance of the same thing to display on everyone's phone should be the goal.
- [x] Scott's phone
- [x] Matt's phone
- [x] Preston's phone
- [x] Duncan's phone

**Comment by scottbot95** [comment]
It runs on all our phones!
